name: ML Pipeline
on:
  push:

env:
  AZURE_RESOURCE_GROUP: "degradai-cpr"
  AZURE_WORKSPACE: "azure-ml-cpr"
  AZURE_LOCATION: "northeurope"
  AZURE_TAGS: "{}"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev

      - name: Run tests
        run: poetry run pytest

  ml-pipeline:
    runs-on: ubuntu-latest
    environment: degradai
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.15"

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

#    - name: setup azure
#      working-directory: train
#      run: ./setup_AzureML.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }}
#
#    - name: Run pipeline
#      working-directory: train
#      run: ./run_AzureML.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }} ${{ env.AZURE_TAGS }}
    - name: Download model
      working-directory: train
      env:
        DOWNLOAD_PATH: "../app"
      run: |
        MODEL_VERSION=3
        echo "Downloading model version $MODEL_VERSION"
        ./run_download_model.sh $MODEL_VERSION ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }} ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.DOWNLOAD_PATH }} 

    - name: Upload Model Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: degradai-model
        path: app/model