name: ML Pipeline
on:
  push:

env:
  AZURE_RESOURCE_GROUP: "degradai-cpr"
  AZURE_WORKSPACE: "azure-ml-cpr"
  AZURE_LOCATION: "northeurope"
  AZURE_TAGS: "{}"


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with dev

      - name: Run tests
        run: poetry run pytest

    ml-pipeline:
      runs-on: ubuntu-latest
      environment: degradai

      steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install

      - name: azure cli version
        run: az --version

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Run pipeline
        run: |
          cd train
          ./setup_AzureML.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }}
          ./run_AzureML.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }} ${{ env.AZURE_TAGS }} 

      - name: Download model
        working-directory: train
        env:
          DOWNLOAD_PATH: "../app"
        run: |
          ./run_download_model.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }} ${{ secrets.SUBSCRIPTION_ID }} ${{ env.DOWNLOAD_PATH }} 

      - name: Upload Model Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Publish model
          path: app/model


