name: ml-pipeline.yml
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

env:
  AZURE_RESOURCE_GROUP: "degradai-cpr"
  AZURE_WORKSPACE: "azure-ml-cpr"
  AZURE_LOCATION: "northeurope"
  AZURE_TAGS: "{}"


jobs:
    ml-pipeline:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"

#      - name: Install Azure CLI
#        run: |
#          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install poetry
            poetry install

      - name: azure login
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Run pipeline
        run: |
          cd train
          ./setup_AzureML.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }}
          ./run_AzureML.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }} ${{ env.AZURE_TAGS }} 

      - name: Download model
        working-directory: train
        env:
          DOWNLOAD_PATH: "../app"
        run: |
          ./run_download_model.sh ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ env.AZURE_RESOURCE_GROUP }} ${{ env.AZURE_WORKSPACE }} ${{ env.AZURE_LOCATION }} ${{ secrets.SUBSCRIPTION_ID }} ${{ env.DOWNLOAD_PATH }} 

      - name: Upload Model Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Publish model
          path: app/model


